### ISSUE TITLE
local_db不存在

### ISSUE THREAD

**Issue by callmesoul** [a597873885/webfunny_servers#1]
local_db不存在回报错，跑不了

**Comment by zhumin042** [comment]
将local_db相关部分注释掉就可以了，如下：config/db.js

`// const sequelizeTemp = require('./local_db')
const Sequelize = require('sequelize');
let db = null
// if (sequelizeTemp) {
//   db = sequelizeTemp.sequelize
// } else {
  const sequelize = new Sequelize('testdb', 'root', '', {
    host: '127.0.0.1',
    dialect: 'mysql',
    operatorsAliases: false,
    dialectOptions: {
      charset: "utf8mb4",
      collate: "utf8mb4_unicode_ci",
      supportBigNumbers: true,
      bigNumberStrings: true
    },

    pool: {
      max: 5,
      min: 0,
      acquire: 30000,
      idle: 10000
    },
    timezone: '+08:00' //东八时区
  });

  db = sequelize

// }

module.exports = {
  sequelize: db
}
`
