### ISSUE TITLE
modules模块报错

### ISSUE THREAD

**Issue by sun-zy** [a597873885/webfunny_servers#1]
modules模块里面，例如 user.js，定义  class UserModel，为什么我的项目会报错，不需要继承extends吗？

**Comment by a597873885** [comment]
@sun-zy  能贴出来具体的错误日志让我看下吗？

**Comment by sun-zy** [comment]
已经解决了，多谢

**Comment by sun-zy** [comment]
> @sun-zy 能贴出来具体的错误日志让我看下吗？

已经解决了，多谢！
